// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0TYA_fuT1dnQcuf-0Iz4-6H1mC6IRoiQ',
    appId: '1:1039435443144:web:fde10185661bfddef16efd',
    messagingSenderId: '1039435443144',
    projectId: 'news-app-4b3a8',
    authDomain: 'news-app-4b3a8.firebaseapp.com',
    storageBucket: 'news-app-4b3a8.appspot.com',
    measurementId: 'G-M19Q22W5ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA0DHRYiDuUX2r2oEIunDOlDlf_0IJfJ0',
    appId: '1:1039435443144:android:b14032e446163923f16efd',
    messagingSenderId: '1039435443144',
    projectId: 'news-app-4b3a8',
    storageBucket: 'news-app-4b3a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAovcnsEufUKqm6aLbbG_xTN_AyKZdPHvQ',
    appId: '1:1039435443144:ios:1c771e659ee0b339f16efd',
    messagingSenderId: '1039435443144',
    projectId: 'news-app-4b3a8',
    storageBucket: 'news-app-4b3a8.appspot.com',
    iosBundleId: 'com.example.newsWatcher',
  );

}